variables:
- template: ../../config-infra-prod.yml

trigger:
- none

stages:
- stage: EndpointInferenceTest
  displayName: Test doing inference on the endpoint
  jobs:
    - job: EndpointInferenceTest
      steps:
      - checkout: self
        path: s/
      - template: /aml-cli-v2/install-az-cli.yml
      - template: /aml-cli-v2/install-aml-cli.yml
      - template: /aml-cli-v2/connect-to-workspace.yml
      - template: /aml-cli-v2/endpoint-inference-test.yml