channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-mlflow==1.56.0
      - azureml-sdk==1.56.0
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - joblib==1.2.0
      - matplotlib==3.8.4